[package]
name = "oner"
version = "1.0.0"
authors = ["Richard Dallaway <richard@dallaway.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
